#!/bin/bash

# Загрузка переменных из .env файла
set -o allexport
source .env
set +o allexport


echo "🔍 Загруженные переменные окружения:"
echo "DB__HOST=$DB__HOST"
echo "DB__PORT=$DB__PORT"
echo "DB__NAME=$DB__NAME"
echo "DB__USER=$DB__USER"
echo "DB__PASSWORD=$DB__PASSWORD"
echo "DEFAULT_ADMIN_USER=$DEFAULT_ADMIN_USER"
echo "DEFAULT_ADMIN_PASSWORD=$DEFAULT_ADMIN_PASSWORD"
echo "SQLALCHEMY_DATABASE_URI=$SQLALCHEMY_DATABASE_URI"
echo "ALEMBIC_CONFIG=$ALEMBIC_CONFIG"
echo "-----------------------------"

# Проверка и установка postgresql-client, если не установлен
if ! command -v psql &> /dev/null; then
    echo "❗ postgresql-client не найден. Устанавливаем..."
    apk update
    apk add --no-cache postgresql16-client
fi

#
## 🔐 Жёстко заданный суперпользователь (используется ТОЛЬКО для создания root)
DEFAULT_ADMIN_USER=$DEFAULT_ADMIN_USER
DEFAULT_ADMIN_PASSWORD=$DEFAULT_ADMIN_PASSWORD

# Функция для проверки существования пользователя
user_exists() {
    local user=$1
    export PGPASSWORD="$DEFAULT_ADMIN_PASSWORD"
    psql -h "$DB__HOST" -p "$DB__PORT" -U "$DEFAULT_ADMIN_USER" -d postgres \
        -tc "SELECT 1 FROM pg_roles WHERE rolname='$user'" | grep -q 1
    return $?
}

# Функция для проверки существования базы данных
database_exists() {
    local db=$1
    export PGPASSWORD="$DEFAULT_ADMIN_PASSWORD"
    psql -h "$DB__HOST" -p "$DB__PORT" -U "$DEFAULT_ADMIN_USER" -d postgres \
        -tc "SELECT 1 FROM pg_database WHERE datname = '$db'" | grep -q 1
    return $?
}

# Функция для проверки применения миграций
migrations_applied() {
    local config=$1
    alembic -c "$config" current | grep -q "head"
    return $?
}

# Создание пользователя (если не существует)
if ! user_exists "$DB__USER"; then
    echo "Создание пользователя $DB__USER..."
    export PGPASSWORD="$DEFAULT_ADMIN_PASSWORD"
    psql -h "$DB__HOST" -p "$DB__PORT" -U "$DEFAULT_ADMIN_USER" -d postgres \
        -c "CREATE USER $DB__USER WITH PASSWORD '$DB__PASSWORD';"
else
    echo "Пользователь $DB__USER уже существует, пропускаем создание."
fi

# Устанавливаем пароль для psql
export PGPASSWORD="$DB__PASSWORD"

# Путь до Alembic конфигурации
ALEMBIC_CONFIG="alembic.ini"

# Создание базы данных (если не существует)
if ! database_exists "$DB__NAME"; then
    echo "Создание базы данных $DB__NAME с владельцем $DB__USER..."
    export PGPASSWORD="$DEFAULT_ADMIN_PASSWORD"
    psql -h "$DB__HOST" -p "$DB__PORT" -U "$DEFAULT_ADMIN_USER" -d postgres \
        -c "CREATE DATABASE $DB__NAME OWNER $DB__USER;"

    # Для существующих баз данных - смена владельца
    psql -h "$DB__HOST" -p "$DB__PORT" -U "$DEFAULT_ADMIN_USER" -d "$DB__NAME" \
        -c "ALTER DATABASE $DB__NAME OWNER TO $DB__USER;"
else
    echo "База данных $DB__NAME уже существует, проверяем владельца..."
    export PGPASSWORD="$DEFAULT_ADMIN_PASSWORD"
    psql -h "$DB__HOST" -p "$DB__PORT" -U "$DEFAULT_ADMIN_USER" -d "$DB__NAME" \
        -c "ALTER DATABASE $DB__NAME OWNER TO $DB__USER;"
fi

ALEMBIC_LOG_FILE="alembic_autogenerate.log"

echo "Проверка изменений в моделях для миграции..."
echo "=== Вывод alembic revision --autogenerate ===" > "$ALEMBIC_LOG_FILE"

# Запускаем alembic, записываем ВЕСЬ вывод в лог и одновременно обрабатываем его
NEW_REV_FILE=$(alembic -c "$ALEMBIC_CONFIG" revision --autogenerate -m "Auto migration" 2>&1 | tee -a "$ALEMBIC_LOG_FILE" | grep "Generating" | awk '{print $2}')

echo "=== Результат обработки ===" >> "$ALEMBIC_LOG_FILE"
echo "NEW_REV_FILE=$NEW_REV_FILE" >> "$ALEMBIC_LOG_FILE"

if [ -n "$NEW_REV_FILE" ] && [ -f "$NEW_REV_FILE" ]; then
    # Проверяем, содержит ли миграция только стандартные комментарии без реальных команд
    if grep -q "pass" "$NEW_REV_FILE" && \
       grep -q "# ### commands auto generated by Alembic" "$NEW_REV_FILE" && \
       [ $(grep -c "op.create_table\|op.drop_table\|op.add_column\|op.drop_column" "$NEW_REV_FILE") -eq 0 ]; then
        echo "❕ Изменений нет, удаляем пустую миграцию: $NEW_REV_FILE"
        rm "$NEW_REV_FILE"
    else
        echo "🚀 Найдена новая миграция: $NEW_REV_FILE, применяем..."
        alembic -c "$ALEMBIC_CONFIG" upgrade head
    fi
else
    echo "✅ Миграции актуальны, изменений не найдено."
fi

echo "✅ Инициализация базы данных завершена."