"""empty message

Revision ID: 0fafbbea2d4d
Revises: f3357a8d8403
Create Date: 2025-12-22 16:09:24.348676

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0fafbbea2d4d"
down_revision: Union[str, None] = "f3357a8d8403"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "leadmagnit",
        sa.Column("email", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_leadmagnit_id"), "leadmagnit", ["id"], unique=False)
    op.create_table(
        "newsletter",
        sa.Column("email", sa.String(length=200), nullable=False),
        sa.Column("form", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_newsletter_id"), "newsletter", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_newsletter_id"), table_name="newsletter")
    op.drop_table("newsletter")
    op.drop_index(op.f("ix_leadmagnit_id"), table_name="leadmagnit")
    op.drop_table("leadmagnit")
    # ### end Alembic commands ###
