"""empty message

Revision ID: f3357a8d8403
Revises:
Create Date: 2025-12-22 11:57:55.588316

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f3357a8d8403"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comments_online",
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("email", sa.String(length=250), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("replay", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default="now()", nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_comments_online_id"), "comments_online", ["id"], unique=False)
    op.create_table(
        "crm_tokens",
        sa.Column("token", sa.String(length=5000), nullable=False),
        sa.Column("refresh_token", sa.String(length=5000), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_crm_tokens_id"), "crm_tokens", ["id"], unique=False)
    op.create_table(
        "form_orders",
        sa.Column("form", sa.String(length=250), nullable=True),
        sa.Column("telegram", sa.String(length=250), nullable=True),
        sa.Column("email", sa.String(length=250), nullable=True),
        sa.Column("phone", sa.String(length=250), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("link", sa.String(length=1500), nullable=True),
        sa.Column("theme_request", sa.String(length=1500), nullable=True),
        sa.Column("promocode", sa.String(length=1250), nullable=True),
        sa.Column("url_form", sa.String(length=1250), nullable=True),
        sa.Column("utm_source", sa.String(length=1500), nullable=True),
        sa.Column("utm_medium", sa.String(length=1500), nullable=True),
        sa.Column("utm_campaign", sa.String(length=1500), nullable=True),
        sa.Column("utm_content", sa.String(length=1500), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default="now()", nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_form_orders_id"), "form_orders", ["id"], unique=False)
    op.create_table(
        "telegram_push_users",
        sa.Column("chat_id", sa.String(length=500), nullable=False),
        sa.Column("send", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Boolean(), nullable=False),
        sa.Column("easypay_online", sa.Boolean(), nullable=False),
        sa.Column("consult", sa.Boolean(), nullable=False),
        sa.Column("buy_account", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_telegram_push_users_id"), "telegram_push_users", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_telegram_push_users_id"), table_name="telegram_push_users")
    op.drop_table("telegram_push_users")
    op.drop_index(op.f("ix_form_orders_id"), table_name="form_orders")
    op.drop_table("form_orders")
    op.drop_index(op.f("ix_crm_tokens_id"), table_name="crm_tokens")
    op.drop_table("crm_tokens")
    op.drop_index(op.f("ix_comments_online_id"), table_name="comments_online")
    op.drop_table("comments_online")
    # ### end Alembic commands ###
