UTM_SOURCE_OLD = 1044269
UTM_MEDIUM_OLD = 1044271
UTM_CAMPAIGN_OLD = 1044273
UTM_CONTENT_OLD = 1044275
UTM_TERM_OLD = 1044277
UTM_SOURCE_FIELD_ID = 1044269
UTM_MEDIUM_FIELD_ID = 1044271
UTM_CAMPAIGN_FIELD_ID = 1044273
UTM_CONTENT_FIELD_ID = 1044275
UTM_TERM_FIELD_ID = 1044277
GOOGLE_ID_FIELD_ID = 1044283
YANDEX_ID_FIELD_ID = 1044285
GOOGLE_ID_FIELD_ID_CONTACT = 1036187
YANDEX_ID_FIELD_ID_CONTACT = 1036185

UTM_SOURCE_FIELD_ID_CONTACT = 1044203
UTM_MEDIUM_FIELD_ID_CONTACT = 1046245
UTM_CAMPAIGN_FIELD_ID_CONTACT = 1046247
UTM_CONTENT_FIELD_ID_CONTACT = 1046249

ROISTAT_VISIT_ID_LEAD = 1046243
ROISTAT_VISIT_ID = 1045935

EP_REQ_ACC = 3
EP_REQ_REGCOMP = 4
EP_REQ_REGLK = 5
EP_REQ_ALL = 6
EP_REQ_NEWSLETTER = 6
EP_REQ_LEAD = 9
EP_REQ_LEAD_COMP = 326
EP_REQ_PAYPLAN = 13

title_form = {
    "myform_menu_ru": "Заявка Общая Меню (попап)",
    "myform_menu_en": "Заявка Общая Меню (попап) EN",
    "myformblog_ru": "Заявка Общая Блог (попап)",
    "myformblog_en": "Заявка Общая Блог (попап) EN",
    "common_vopros_ru": "Вопрос Общий (форма)",
    "common_vopros_en": "Вопрос Общий (форма) EN",
    "leadmagnit_ru": "Скачивание лидмагнита",
    "leadmagnit_en": "Скачивание лидмагнита EN",
    "newsletter_form_ru": "Подписка на рассылку (форма)",
    "newsletter_form_en": "Подписка на рассылку (форма) EN",
    "newsletter_popup_ru": "Подписка на рассылку (попап)",
    "newsletter_popup_en": "Подписка на рассылку (попап) EN",
    "myformblog_right_ru": "Заявка Общая Блог (справа)",
    "myformblog_right_en": "Заявка Общая Блог (справа) EN",
    "myformblog_company_ru": "Заявка Компании Блог (промоблок)",
    "myformblog_company_en": "Заявка Компании Блог (промоблок) EN",
    "myformblog_payments_ru": "Заявка Платежка Блог (промоблок)",
    "myformblog_payments_en": "Заявка Платежка Блог (промоблок) EN",
    "myformnew_ru": "Заявка Платежка (попап)",
    "myformnew_en": "Заявка Платежка EN (общая) (попап)",
    "myformstnew_ru": "Заявка Платежка Standard (попап)",
    "myformstnew_en": "Заявка Платежка Standard EN (попап)",
    "manual_ru": "Заявка Платежка Ручное подключение (попап)",
    "manual_en": "Заявка Платежка Ручное подключение (попап) EN",
    "vopros_ru": "Вопрос Платежка (форма)",
    "vopros_en": "Вопрос Платежка (форма) EN",
    "call_company_uk_ru": "Обратный звонок Великобритания (попап)",
    "call_company_uk_en": "Обратный звонок Великобритания (попап) EN",
    "call_company_ru": "Обратный звонок Компании (попап)",
    "call_company_en": "Обратный звонок Компании (попап) EN",
    "consult_company_ru": "Консультация по компании (попап)",
    "consult_company_en": "Консультация по компании (попап) EN",
    "company_vopros_ru": "Вопрос по компании (форма)",
    "company_vopros_en": "Вопрос по компании (форма) EN",
    "consult_company_uk_ru": "Консультация Великобритания (попап)",
    "consult_company_uk_en": "Консультация Великобритания (попап) EN",
    "сompany_vopros_uk_ru": "Вопрос Великобритания (форма)",
    "сompany_vopros_uk_en": "Вопрос Великобритания (форма) EN",
    "company_uk_start_ru": "Заявка Компания UK Start (попап)",
    "company_uk_start_en": "Заявка Компания UK Start (попап) EN",
    "company_uk_stripe_ru": "Заявка Компания UK Stripe (попап)",
    "company_uk_stripe_en": "Заявка Компания UK Stripe (попап) EN",
    "company_uk_paypal_ru": "Заявка Компания UK Paypal (попап)",
    "company_uk_paypal_en": "Заявка Компания UK Paypal (попап) EN",
    "paid_consultation_ru": "Заявка UK Consulting",
    "paid_consultation_en": "Заявка UK Consulting EN",
    "consult_company_uae_ru": "Консультация ОАЭ (попап)",
    "consult_company_uae_en": "Консультация ОАЭ (попап) EN",
    "call_company_uae_ru": "Обратный звонок ОАЭ (попап)",
    "call_company_uae_en": "Обратный звонок ОАЭ (попап) EN",
    "сompany_vopros_uae_ru": "Вопрос ОАЭ (форма)",
    "сompany_vopros_uae_en": "Вопрос ОАЭ (форма) EN",
    "call_company_usa_ru": "Обратный звонок США (попап)",
    "call_company_usa_en": "Обратный звонок США (попап) EN",
    "consult_company_usa_ru": "Консультация США (попап)",
    "consult_company_usa_en": "Консультация США (попап) EN",
    "сompany_vopros_usa_ru": "Вопрос США (форма)",
    "сompany_vopros_usa_en": "Вопрос США (форма) EN",
    "call_company_cyprus_ru": "Обратный звонок Кипр (попап)",
    "call_company_cyprus_en": "Обратный звонок Кипр (попап) EN",
    "consult_company_cyprus_ru": "Консультация Кипр (попап)",
    "consult_company_cyprus_en": "Консультация Кипр (попап) EN",
    "сompany_vopros_cyprus_en": "Вопрос Кипр (форма) EN",
    "call_company_malta_ru": "Обратный звонок Мальта (попап)",
    "call_company_malta_en": "Обратный звонок Мальта (попап) EN",
    "consult_company_malta_ru": "Консультация Мальта (попап)",
    "consult_company_malta_en": "Консультация Мальта (попап) EN",
    "сompany_vopros_malta_ru": "Вопрос Мальта (форма)",
    "сompany_vopros_malta_en": "Вопрос Мальта (форма) EN",
    "banking_cards_kz_vopros_ru": "Вопрос Казахстан (форма)",
    "banking_cards_kg_vopros_ru": "Вопрос Киргизия (форма)",
    "banking_cards_uz_vopros_ru": "Вопрос Узбекистан (форма)",
    "banking_cards_turkey_vopros_ru": "Вопрос Турция (форма)",
    "bank_account_ru": "Европейская виртуальная карта",
    "bank_account": "Европейская виртуальная карта",
    "company-baltics_ru": "Company Baltics",
    "company-baltics_En": "Company Baltics en",
    "company-baltics_en": "Company Baltics en",
    "company-uk_ru": "Company UK",
    "company-uk_En": "Company UK (en)",
    "company-uk_en": "Company UK (en)",
    "company-uk-basic_ru": "Business Basic",
    "company-uk-basic_En": "Business Basic (en)",
    "company-uk-basic_en": "Business Basic (en)",
    "company-uk-pro_ru": "Business PRO",
    "company-uk-pro_En": "Business PRO (en)",
    "company-uk-pro_en": "Business PRO (en)",
    "company_uk_start_En": "Business START (en)",
    "company-uk-start_en": "Business START (en)",
    "myformmulti_ru": "Подключение Stripe Multi",
    "myformmulti_En": "Подключение Stripe Multi (en)",
    "myformmulti_en": "Подключение Stripe Multi (en)",
    "myformmultionline-school_ru": "Подключение Тарифа Multi Online School",
    "myformmultionline-school_En": "Подключение Тарифа Multi Online School (en)",
    "myformmultionline-school_en": "Подключение Тарифа Multi Online School (en)",
    "myformmultionline-tool_ru": "Подключение Тарифа Multi Online Tool",
    "myformmultionline-tool_En": "Подключение Тарифа Multi Online Tool (en)",
    "myformmultionline-tool_en": "Подключение Тарифа Multi Online Tool (en)",
    "myformmultihigh-risk_ru": "Подключение Тарифа Multi High-Risk",
    "myformmultihigh-risk_En": "Подключение Тарифа Multi High-Risk (en)",
    "myformmultihigh-risk_en": "Подключение Тарифа Multi High-Risk (en)",
    "myformnewonline-school_ru": "Подключение Stripe Online School",
    "myformnewonline-school_En": "Подключение Stripe Online School(en)",
    "myformnewonline-school_en": "Подключение Stripe Online School(en)",
    "myformnewonline-tool_ru": "Подключение Stripe Online Tool",
    "myformnewonline-tool_En": "Подключение Stripe Online Tool(en)",
    "myformnewonline-tool_en": "Подключение Stripe Online Tool(en)",
    "myformnewhigh-risk_ru": "Подключение Stripe High-Risk",
    "myformnewhigh-risk_En": "Подключение Stripe High-Risk(en)",
    "myformnewhigh-risk_en": "Подключение Stripe High-Risk(en)",
    "myformpronew_ru": "Подключение Stripe Basic",
    "myformpronew_En": "Подключение Stripe Basic(en)",
    "myformpronew_en": "Подключение Stripe Basic(en)",
    "myformpronewonline-school_ru": "Подключение Stripe Basic Online School",
    "myformpronewonline-school_En": "Подключение Stripe Basic Online School(en)",
    "myformpronewonline-school_en": "Подключение Stripe Basic Online School(en)",
    "myformpronewonline-tool_ru": "Подключение Stripe Basic Online Tool",
    "myformpronewonline-tool_En": "Подключение Stripe Basic Online Tool(en)",
    "myformpronewonline-tool_en": "Подключение Stripe Basic Online Tool(en)",
    "myformpronewhigh-risk_ru": "Подключение Stripe Basic High-Risk",
    "myformpronewhigh-risk_En": "Подключение Stripe Basic High-Risk(en)",
    "myformpronewhigh-risk_en": "Подключение Stripe Basic High-Risk(en)",
    "myformstnew_En": "Подключение Stripe Start(en)",
    "myformstnewonline-school_ru": "Подключение Stripe Start Online School",
    "myformstnewonline-school_En": "Подключение Stripe Start Online School(en)",
    "myformstnewonline-school_en": "Подключение Stripe Start Online School(en)",
    "myformstnewonline-tool_ru": "Подключение Stripe Start Online Tool",
    "myformstnewonline-tool_En": "Подключение Stripe Start Online Tool(en)",
    "myformstnewonline-tool_en": "Подключение Stripe Start Online Tool(en)",
    "myformstnewhigh-risk_ru": "Подключение Stripe Start High-Risk",
    "myformstnewhigh-risk_En": "Подключение Stripe Start High-Risk(en)",
    "myformstnewhigh-risk_en": "Подключение Stripe Start High-Risk(en)",
    "affiliate_ru": "Аффилейт",
    "affiliate_En": "Аффилейт(en)",
    "affiliate_en": "Аффилейт(en)",
    "manual_En": "Мануал(en)",
    "company_uae_ru": "ОАЭ",
    "company_uae_En": "ОАЭ(en)",
    "company_cyprus_ru": "Кипр",
    "company_cyprus_En": "Кипр(en)",
    "company_malta_ru": "Мальта",
    "company_malta_En": "Мальта(en)",
    "сompany_vopros_cyprus_ru": "Вопрос по компании CYPRUS",
    "consult_banking_cards_kg_3_ru": "Зарубежные карты Киргизия 220",
    "consult_banking_cards_uz_1_ru": " Зарубежные карты Узбекистан 590",
    "consult_banking_cards_kz_iin_ru": "ИИН В Казахстане",
    "consult_banking_cards_sng_3_ru": "Банк Азии 220",
    "company_freezone_uae_ru": "Регистрация ОАЭ Free Zone",
    "company_freezone_visa_uae_ru": "Регистрация ОАЭ Free Zone + виза",
    "company_mainland_uae_ru": "Регистрация ОАЭ Mainland",
    "company_mainland_visa_uae_ru": " Регистрация ОАЭ Mainland + виза",
}

form_titles = {
    "myformnew_ru": "Общая (консультация)",
    "common_vopros_ru": "Общая (вопрос)",
    "consult_company_ru": "Регистрация компаний (консультация)",
    "consult_company_uk_ru": "Регистрация Англия (консультация)",
    "consult_company_usa_ru": "Регистрация США (консультация)",
    "consult_company_cyprus_ru": "Регистрация Кипр (консультация)",
    "consult_company_uae_ru": "Регистрация ОАЭ (консультация)",
    "company_vopros_ru": "Регистрация компаний (вопрос)",
    "company_business_uk_ru": "Регистрация Англия Business",
    "company_business_basic_uk_ru": "Регистрация Англия Basic",
    "company_business_stripe_uk_ru": "Регистрация Англия Stripe",
    "company_business_paypal_uk_ru": "Регистрация Англия Paypal",
    "company_vopros_uk_ru": "Регистрация Англия (вопрос)",
    "company_business_usa_ru": "Регистрация США Business",
    "company_business_basic_usa_ru": "Регистрация США Basic",
    "company_vopros_usa_ru": "Регистрация США (вопрос)",
    "company_business_cyprus_ru": "Регистрация Кипр Business",
    "company_business_basic_cyprus_ru": "Регистрация Кипр Basic",
    "company_business_stripe_cyprus_ru": "Регистрация Кипр Stripe",
    "company_vopros_cyprus_ru": "Регистрация Кипр (вопрос)",
    "consult_payments_shopify_ru": "Прием платежей Shopify Payments",
    "company_freezone_uae_ru": "Регистрация ОАЭ Free Zone",
    "company_freezone_visa_uae_ru": "Регистрация ОАЭ Free Zone + виза",
    "company_mainland_uae_ru": "Регистрация ОАЭ Mainland",
    "company_mainland_visa_uae_ru": " Регистрация ОАЭ Mainland + виза",
    "company_business_uae_ru": "Регистрация ОАЭ 1 учр",
    "company_business_basic_uae_ru": "Регистрация ОАЭ 2 учр",
    "company_business_pro_uae": "Регистрация ОАЭ 3 учр",
    "company_vopros_uae_ru": "Регистрация ОАЭ (вопрос)",
    "consult_payments_ru": "Прием платежей (консультация)",
    "consult_payments_stripe_ru": "Прием платежей Stripe",
    "consult_payments_paypal_ru": "Прием платежей Paypal",
    "payments_vopros_ru": "Прием платежей (вопрос)",
    "consult_marketplaces_ru": "Маркетплейсы (консультация)",
    "consult_marketplaces_amazon_ru": "Маркетплейсы Amazon",
    "consult_marketplaces_etsy_ru": "Маркетплейсы Etsy",
    "consult_company_marketplaces_ru": "Маркетплейсы Компания",
    "marketplaces_vopros_ru": "Маркетплейсы (вопрос)",
    "consult_companysale_ru": "Готовые компании (консультация)",
    "consult_companysale_cyprus_ru": "Готовые компании Кипр",
    "consult_companysale_hongkong_ru": "Готовые компании Гонконг",
    "companysale_vopros_ru": "Готовые компании (вопрос)",
    "consult_banking_ru": "Банки (консультация)",
    "banking_vopros_ru": "Банки (вопрос)",
    "consult_banking_business_ru": "Онлайн-банки (консультация)",
    "consult_banking_business_wise_ru": "Онлайн-банки Wise",
    "consult_banking_business_payoneer_ru": "Онлайн-банки Payoneer",
    "banking_business_vopros_ru": "Онлайн-банки (вопрос)",
    "consult_banking_cards_ru": "Зарубежные карты (консультация)",
    "consult_banking_cards_sng_1_ru": "IBT Банк Таджикистан 390",
    "consult_banking_cards_sng_2_ru": "IBT Банк (вирт.) Таджикистан 180",
    "consult_banking_cards_uae_ru": "Зарубежные карты ОАЭ",
    "consult_banking_cards_kg_ru": "Зарубежные карты Киргизия",
    "consult_banking_cards_turkey_ru": "Зарубежные карты Турция",
    "consult_banking_cards_kz_ru": "Зарубежные карты Казахстан",
    "banking_cards_vopros_ru": "Зарубежные карты (вопрос)",
    "banking_cards_kz_vopros_ru": "Вопрос Казахстан (форма)",
    "banking_cards_kg_vopros_ru": "Вопрос Киргизия (форма)",
    "banking_cards_uz_vopros_ru": "Вопрос Узбекистан (форма)",
    "banking_cards_turkey_vopros_ru": "Вопрос Турция (форма)",
    "consult_ru": "Бесплатная консультация",
    "consult_paid_ru": "Платная консультация",
    "consulting_vopros_ru": "Консультация (вопрос)",
    "myformblog_ru": "Общая Блог",
    "myformblog_right_ru": "Общая Блог (форма справа)",
    "myformblog_company_ru": "Регистрация компаний Блог",
    "myformblog_payments_ru": "Прием платежей Блог",
    "myformblog_banking_business_ru": "Онлайн-банки Блог",
    "myformblog_banking_cards_ru": "Зарубежные карты Блог",
    "myformblog_marketplaces_ru": "Маркетплейсы Блог",
    "leadmagnit_ru": "Лид-магнит (прием платежей)",
    "leadmagnit_company_ru": "Лид-магнит (регистрация компаний)",
    "newsletter_form_ru": "Подписка на рассылку (форма)",
    "newsletter_popup_ru": "Подписка на рассылку (попап)",
    "partners_ru": "Сотрудничество (консультация)",
    "vopros_partners_ru": "Сотрудничество (вопрос)",
    "consult_banking_cards_kz_1_ru": "Казахстан",
    "consult_banking_cards_kg_1_ru": "MBANK Киргизия 290",
    "consult_banking_cards_kg_2_ru": "Бакай Банк Киргизия 390",
    "consult_banking_cards_turkey_1_ru": "Зарубежные карты Турция 290",
    "consult_banking_cards_kz_2_ru": "Зарубежные карты Казахстан 690",
    "consult_banking_cards_turkey_2_ru": "Ziraat Банк Турция 1250",
    "consult_banking_cards_turkey_3_ru": "Зарубежные карты Турция 1190",
    "consult_banking_cards_sng_3_ru": "Банк Азии 220",
    "consult_company_hk_ru": "Регистрация Гонконг (консультация)",
    "company_business_hk_ru": "Регистрация Гонконг Business",
    "company_business_basic_hk_ru": "Регистрация Гонконг Basic",
    "company_sale_hk_ru": "Покупка компании Гонконг",
    "company_vopros_hk_ru": "Регистрация Гонконг (вопрос)",
    "consult_banking_cards_kg_3_ru": "Айыл Банк Киргизия 290",
    "consult_banking_cards_uz_1_ru": " Зарубежные карты Узбекистан 590",
    "consult_banking_cards_kz_iin_ru": "ИИН В Казахстане",
}

# Константы для Easy Payments
EASY_PAYMENTS_SUBSCRIPTION = 142  # Подписка на рассылку
EASY_PAYMENTS_LEAD_MAGNET = 9  # Лид-магнит
EASY_PAYMENTS_LEAD_MAGNET_COMPANIES = 326  # Лид-магнит (компании)
EASY_PAYMENTS_GENERAL_BASE = 6  # Общая база
EASY_PAYMENTS_GENERAL_BASE_PASSED = 7  # Общая база (прошли)
EASY_PAYMENTS_APPLICATIONS_GENERAL_FORM = 555  # Заявки (общая форма)
EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION = 4  # Заявки (регистрация компаний)
EASY_PAYMENTS_APPLICATIONS_PAYMENT_PROCESSING = 3  # Заявки (прием платежей)
EASY_PAYMENTS_APPLICATIONS_ACCOUNT_OPENING = 556  # Заявки (открытие счетов)
EASY_PAYMENTS_APPLICATIONS_ONLINE_BANK_BUSINESS_ACCOUNTS = 557  # Заявки (бизнес-счета в онлайн-банках)
EASY_PAYMENTS_APPLICATIONS_OVERSEAS_CARDS = 558  # Заявки (зарубежные карты)
EASY_PAYMENTS_APPLICATIONS_MARKETPLACES_REGISTRATION = 559  # Заявки (регистрация на маркетплейсах)
EASY_PAYMENTS_APPLICATIONS_READY_COMPANIES = 560  # Заявки (готовые компании)
EASY_PAYMENTS_APPLICATIONS_PARTNERSHIP = 561  # Заявки (сотрудничество)

QUALIFICATION_PIPLINE = 7444098
EMAIL_PIPLINE = 4942291
PARTNERSHIP_PIPLINE = 7444274

forms_to_pipelines_mapper = {
    "myformnew_ru": QUALIFICATION_PIPLINE,
    "common_vopros_ru": QUALIFICATION_PIPLINE,
    "consult_company_ru": QUALIFICATION_PIPLINE,
    "consult_company_uk_ru": QUALIFICATION_PIPLINE,
    "consult_company_usa_ru": QUALIFICATION_PIPLINE,
    "consult_company_cyprus_ru": QUALIFICATION_PIPLINE,
    "consult_company_uae_ru": QUALIFICATION_PIPLINE,
    "company_vopros_ru": QUALIFICATION_PIPLINE,
    "company_business_uk_ru": QUALIFICATION_PIPLINE,
    "company_business_basic_uk_ru": QUALIFICATION_PIPLINE,
    "company_business_stripe_uk_ru": QUALIFICATION_PIPLINE,
    "consult_payments_shopify_ru": QUALIFICATION_PIPLINE,
    "company_business_paypal_uk_ru": QUALIFICATION_PIPLINE,
    "company_vopros_uk_ru": QUALIFICATION_PIPLINE,
    "company_business_usa_ru": QUALIFICATION_PIPLINE,
    "company_business_basic_usa_ru": QUALIFICATION_PIPLINE,
    "company_vopros_usa_ru": QUALIFICATION_PIPLINE,
    "company_business_cyprus_ru": QUALIFICATION_PIPLINE,
    "company_business_basic_cyprus_ru": QUALIFICATION_PIPLINE,
    "company_business_stripe_cyprus_ru": QUALIFICATION_PIPLINE,
    "company_vopros_cyprus_ru": QUALIFICATION_PIPLINE,
    "company_freezone_uae_ru": QUALIFICATION_PIPLINE,
    "company_freezone_visa_uae_ru": QUALIFICATION_PIPLINE,
    "company_mainland_uae_ru": QUALIFICATION_PIPLINE,
    "company_mainland_visa_uae_ru": QUALIFICATION_PIPLINE,
    "company_business_uae_ru": QUALIFICATION_PIPLINE,
    "company_business_basic_uae_ru": QUALIFICATION_PIPLINE,
    "company_business_pro_uae": QUALIFICATION_PIPLINE,
    "company_vopros_uae_ru": QUALIFICATION_PIPLINE,
    "consult_payments_ru": QUALIFICATION_PIPLINE,
    "consult_payments_stripe_ru": QUALIFICATION_PIPLINE,
    "consult_payments_paypal_ru": QUALIFICATION_PIPLINE,
    "payments_vopros_ru": QUALIFICATION_PIPLINE,
    "consult_marketplaces_ru": QUALIFICATION_PIPLINE,
    "consult_marketplaces_amazon_ru": QUALIFICATION_PIPLINE,
    "consult_marketplaces_etsy_ru": QUALIFICATION_PIPLINE,
    "consult_company_marketplaces_ru": QUALIFICATION_PIPLINE,
    "marketplaces_vopros_ru": QUALIFICATION_PIPLINE,
    "consult_companysale_ru": QUALIFICATION_PIPLINE,
    "consult_companysale_cyprus_ru": QUALIFICATION_PIPLINE,
    "consult_companysale_hongkong_ru": QUALIFICATION_PIPLINE,
    "companysale_vopros_ru": QUALIFICATION_PIPLINE,
    "banking_cards_kz_vopros_ru": QUALIFICATION_PIPLINE,
    "banking_cards_kg_vopros_ru": QUALIFICATION_PIPLINE,
    "banking_cards_uz_vopros_ru": QUALIFICATION_PIPLINE,
    "banking_cards_turkey_vopros_ru": QUALIFICATION_PIPLINE,
    "consult_banking_ru": QUALIFICATION_PIPLINE,
    "banking_vopros_ru": QUALIFICATION_PIPLINE,
    "consult_banking_business_ru": QUALIFICATION_PIPLINE,
    "consult_banking_business_wise_ru": QUALIFICATION_PIPLINE,
    "consult_banking_business_payoneer_ru": QUALIFICATION_PIPLINE,
    "banking_business_vopros_ru": QUALIFICATION_PIPLINE,
    "consult_banking_cards_ru": QUALIFICATION_PIPLINE,
    "consult_banking_cards_sng_1_ru": QUALIFICATION_PIPLINE,
    "consult_banking_cards_sng_2_ru": QUALIFICATION_PIPLINE,
    "consult_banking_cards_uae_ru": QUALIFICATION_PIPLINE,
    "consult_banking_cards_kg_ru": QUALIFICATION_PIPLINE,
    "consult_banking_cards_turkey_ru": QUALIFICATION_PIPLINE,
    "consult_banking_cards_kz_ru": QUALIFICATION_PIPLINE,
    "banking_cards_vopros_ru": QUALIFICATION_PIPLINE,
    "consult_ru": QUALIFICATION_PIPLINE,
    "consult_paid_ru": QUALIFICATION_PIPLINE,
    "consulting_vopros_ru": QUALIFICATION_PIPLINE,
    "myformblog_ru": QUALIFICATION_PIPLINE,
    "myformblog_right_ru": QUALIFICATION_PIPLINE,
    "myformblog_company_ru": QUALIFICATION_PIPLINE,
    "myformblog_payments_ru": QUALIFICATION_PIPLINE,
    "myformblog_banking_business_ru": QUALIFICATION_PIPLINE,
    "myformblog_banking_cards_ru": QUALIFICATION_PIPLINE,
    "myformblog_marketplaces_ru": QUALIFICATION_PIPLINE,
    "leadmagnit_ru": EMAIL_PIPLINE,
    "leadmagnit_company_ru": EMAIL_PIPLINE,
    "newsletter_form_ru": EMAIL_PIPLINE,
    "newsletter_popup_ru": EMAIL_PIPLINE,
    "partners_ru": PARTNERSHIP_PIPLINE,
    "vopros_partners_ru": PARTNERSHIP_PIPLINE,
    "consult_banking_cards_kz_1_ru": QUALIFICATION_PIPLINE,
    "consult_banking_cards_kg_1_ru": QUALIFICATION_PIPLINE,
    "consult_banking_cards_kg_2_ru": QUALIFICATION_PIPLINE,
    "consult_banking_cards_turkey_1_ru": QUALIFICATION_PIPLINE,
    "consult_banking_cards_kz_2_ru": QUALIFICATION_PIPLINE,
    "consult_banking_cards_turkey_2_ru": QUALIFICATION_PIPLINE,
    "consult_banking_cards_turkey_3_ru": QUALIFICATION_PIPLINE,
    "consult_banking_cards_kg_3_ru": QUALIFICATION_PIPLINE,
    "consult_banking_cards_uz_1_ru": QUALIFICATION_PIPLINE,
    "consult_banking_cards_kz_iin_ru": QUALIFICATION_PIPLINE,
    "consult_banking_cards_sng_3_ru": QUALIFICATION_PIPLINE,
    "consult_company_hk_ru": QUALIFICATION_PIPLINE,
    "company_business_hk_ru": QUALIFICATION_PIPLINE,
    "company_business_basic_hk_ru": QUALIFICATION_PIPLINE,
    "company_sale_hk_ru": QUALIFICATION_PIPLINE,
    "company_vopros_hk_ru": QUALIFICATION_PIPLINE,
}

forms_to_lists_mapper = {
    "myformnew_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_GENERAL_FORM],
    "common_vopros_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_GENERAL_FORM],
    "consult_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_GENERAL_FORM],
    "consult_paid_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_GENERAL_FORM],
    "consulting_vopros_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_GENERAL_FORM],
    "myformblog_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_GENERAL_FORM],
    "myformblog_right_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_GENERAL_FORM],
    "consult_company_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION],
    "consult_company_uk_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION],
    "consult_company_usa_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION],
    "consult_company_cyprus_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION,
    ],
    "consult_company_uae_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION],
    "consult_banking_cards_kg_3_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION,
    ],
    "consult_banking_cards_uz_1_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION,
    ],
    "consult_banking_cards_kz_iin_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION,
    ],
    "company_vopros_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION],
    "company_business_uk_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION],
    "company_business_basic_uk_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION,
    ],
    "company_business_stripe_uk_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION,
    ],
    "consult_payments_shopify_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION,
    ],
    "company_business_paypal_uk_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION,
    ],
    "company_vopros_uk_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION],
    "company_business_usa_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION,
    ],
    "company_business_basic_usa_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION,
    ],
    "company_vopros_usa_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION],
    "company_business_cyprus_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION,
    ],
    "company_business_basic_cyprus_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION,
    ],
    "company_business_stripe_cyprus_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION,
    ],
    "company_vopros_cyprus_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION,
    ],
    "company_business_uae_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION,
    ],
    "company_freezone_uae_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION,
    ],
    "company_freezone_visa_uae_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION,
    ],
    "company_mainland_uae_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION,
    ],
    "company_mainland_visa_uae_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION,
    ],
    "company_business_basic_uae_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION,
    ],
    "company_vopros_uae_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION],
    "myformblog_company_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION],
    "consult_payments_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_PAYMENT_PROCESSING],
    "consult_payments_stripe_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_PAYMENT_PROCESSING,
    ],
    "consult_payments_paypal_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_PAYMENT_PROCESSING,
    ],
    "payments_vopros_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_PAYMENT_PROCESSING],
    "myformblog_payments_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_PAYMENT_PROCESSING],
    "consult_marketplaces_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_MARKETPLACES_REGISTRATION,
    ],
    "consult_marketplaces_amazon_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_MARKETPLACES_REGISTRATION,
    ],
    "consult_marketplaces_etsy_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_MARKETPLACES_REGISTRATION,
    ],
    "consult_company_marketplaces_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_MARKETPLACES_REGISTRATION,
    ],
    "marketplaces_vopros_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_MARKETPLACES_REGISTRATION,
    ],
    "myformblog_marketplaces_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_MARKETPLACES_REGISTRATION,
    ],
    "consult_companysale_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_READY_COMPANIES],
    "consult_companysale_cyprus_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_READY_COMPANIES,
    ],
    "consult_companysale_hongkong_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_READY_COMPANIES,
    ],
    "companysale_vopros_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_READY_COMPANIES],
    "banking_cards_kz_vopros_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_READY_COMPANIES],
    "banking_cards_kg_vopros_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_READY_COMPANIES],
    "banking_cards_uz_vopros_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_READY_COMPANIES],
    "banking_cards_turkey_vopros_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_READY_COMPANIES,
    ],
    "consult_banking_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_ACCOUNT_OPENING],
    "banking_vopros_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_ACCOUNT_OPENING],
    "consult_banking_business_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_ONLINE_BANK_BUSINESS_ACCOUNTS,
    ],
    "consult_banking_business_wise_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_ONLINE_BANK_BUSINESS_ACCOUNTS,
    ],
    "consult_banking_business_payoneer_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_ONLINE_BANK_BUSINESS_ACCOUNTS,
    ],
    "banking_business_vopros_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_ONLINE_BANK_BUSINESS_ACCOUNTS,
    ],
    "myformblog_banking_business_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_ONLINE_BANK_BUSINESS_ACCOUNTS,
    ],
    "consult_banking_cards_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_OVERSEAS_CARDS],
    "consult_banking_cards_sng_1_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_OVERSEAS_CARDS,
    ],
    "consult_banking_cards_sng_2_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_OVERSEAS_CARDS,
    ],
    "consult_banking_cards_uae_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_OVERSEAS_CARDS],
    "consult_banking_cards_kg_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_OVERSEAS_CARDS],
    "consult_banking_cards_turkey_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_OVERSEAS_CARDS,
    ],
    "consult_banking_cards_kz_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_OVERSEAS_CARDS],
    "banking_cards_vopros_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_OVERSEAS_CARDS],
    "myformblog_banking_cards_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_OVERSEAS_CARDS],
    "leadmagnit_ru": [EASY_PAYMENTS_LEAD_MAGNET],
    "leadmagnit_company_ru": [EASY_PAYMENTS_LEAD_MAGNET_COMPANIES],
    "newsletter_form_ru": [EASY_PAYMENTS_SUBSCRIPTION],
    "newsletter_popup_ru": [EASY_PAYMENTS_SUBSCRIPTION],
    "partners_ru": [EASY_PAYMENTS_APPLICATIONS_PARTNERSHIP],
    "vopros_partners_ru": [EASY_PAYMENTS_APPLICATIONS_PARTNERSHIP],
    "consult_banking_cards_kz_1_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_OVERSEAS_CARDS,
    ],
    "consult_banking_cards_kg_1_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_OVERSEAS_CARDS,
    ],
    "consult_banking_cards_kg_2_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_OVERSEAS_CARDS,
    ],
    "consult_banking_cards_turkey_1_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_OVERSEAS_CARDS,
    ],
    "consult_banking_cards_kz_2_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_OVERSEAS_CARDS,
    ],
    "consult_banking_cards_turkey_2_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_OVERSEAS_CARDS,
    ],
    "consult_banking_cards_turkey_3_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_OVERSEAS_CARDS,
    ],
    "consult_banking_cards_sng_3_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_OVERSEAS_CARDS,
    ],
    "consult_company_hk_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION],
    "company_business_hk_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION],
    "company_business_basic_hk_ru": [
        EASY_PAYMENTS_GENERAL_BASE,
        EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION,
    ],
    "company_sale_hk_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION],
    "company_vopros_hk_ru": [EASY_PAYMENTS_GENERAL_BASE, EASY_PAYMENTS_APPLICATIONS_COMPANY_REGISTRATION],
}
